language: node_js
node_js: 
- 18.17.0
cache: npm 

install:
  - npm ci
  - npm i -g
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: gh-pages
    